### ISSUE TITLE
`@RequestScope` doesn't work when resolving fields of >2nd level in the query

### ISSUE THREAD

**Issue by maxkomarychev** [micronaut-projects/micronaut-graphql#483]
### Expected Behavior

I want to be able to access beans with `@RequestScope` while processing the request.

### Actual Behaviour

Error `Exception while fetching data (/books[1]/author) : No request present`

### Steps To Reproduce

Reproducible demo is available here: https://github.com/maxkomarychev/micronaut-graphql-kotlin-request-scope

### Version

4.2.0

**Comment by jeremyg484** [comment]
The issue in your example is one of the Micronaut [PropagatedContext](https://docs.micronaut.io/latest/guide/index.html#contextPropagation) not being available at the point your `@RequestScope` repository is invoked.

The reason the context is not available is because of the call in `AuthorDataLoader` to `CompletableFuture.supplyAsync`, which ultimately results in the repository being invoked on a different thread from the original HTTP request.

The simplest thing to do that fixes this particular example is to change that call to something like:

```
CompletableFuture.supplyAsync( PropagatedContext.wrapCurrent( Supplier {
    ids.map { id -> authorRepository.getAuthor(id) }
}))
```            

I have looked for a more general solution that we might be able to provide in the module, but there are a lot of places in GraphQL where threads can be created outside of Micronaut's control, and in cases like this where you are spawning the thread manually, there's definitely nothing we can really do other than point you to how to propagate the context to a new thread as above. 

We could possibly consider providing an implementation of GraphQL's `Instrumentation` interface that could conceivably add the context at the right point in the majority of cases, but it again would not help in this particular case.

**Comment by maxkomarychev** [comment]
Thanks for the answer and the suggestion - I will give it a shot this week!

**Comment by jeremyg484** [comment]
@maxkomarychev No problem. I'm going to close this for now as I don't see anything concrete that we can change, but we can re-open if some new information emerges.
